In [72]:
import numpy as np
import logging 
# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger()

###### Custom Imports 

from LoadData import * 
from Stats import *

data = load_data('train.csv')
if data is None:
    print("Failed to load data.")
outdf_numeric = CalBasicStats(data,'numeric')
outdf_nonnumeric = CalBasicStats(data,'Non-numeric')

INFO:root:Dataset loaded successfully. Size: (101763, 24) (rows, columns).

In [73]:
FilterConditions =['%Missing','%Zero']
SelectedCols=[]

In [67]:
outdf_numeric

,ColumnName,AllCounts,NotNullCounts,UniqueCounts,%Zero,%Missing,Min,Max,Mean,Average,Median,StddDev,Var,Skewness,Kurtosis,25Percentile,50Percentile,75Percentile
0,id,101763,101763,101763,0.000983,0.0,0.0,101762.00,50881.000000,50881.000000,50881.00,29376.447720,8.629757e+08,0.000000,-1.200000,25440.50,50881.00,76321.50
0,loc,101763,101763,378,0.000000,0.0,1.0,3442.00,37.347160,37.347160,22.00,54.600133,2.981175e+03,11.818737,352.147757,13.00,22.00,42.00
0,v(g),101763,101763,106,0.000000,0.0,1.0,404.00,5.492684,5.492684,3.00,7.900816,6.242290e+01,14.258421,501.401566,2.00,3.00,6.00
0,ev(g),101763,101763,71,0.000000,0.0,1.0,165.00,2.845022,2.845022,1.00,4.631239,2.144837e+01,6.513402,96.033031,1.00,1.00,3.00
0,iv(g),101763,101763,84,0.000000,0.0,1.0,402.00,3.498826,3.498826,2.00,5.534514,3.063084e+01,28.209548,1564.031872,1.00,2.00,4.00
0,n,101763,101763,836,7.699262,0.0,0.0,8441.00,96.655995,96.655995,51.00,171.146350,2.929107e+04,9.908368,209.563305,25.00,51.00,111.00
0,v,101763,101763,4515,7.727760,0.0,0.0,80843.08,538.280956,538.280956,232.79,1270.785357,1.614895e+06,15.959633,518.187094,97.67,232.79,560.25
0,l,101763,101763,55,7.762153,0.0,0.0,1.00,0.111634,0.111634,0.09,0.100095,1.001909e-02,1.903309,5.031641,0.05,0.09,0.15
0,d,101763,101763,3360,7.734638,0.0,0.0,418.20,13.681881,13.681881,9.82,14.121237,1.994093e+02,5.617998,92.417668,5.60,9.82,18.00
0,i,101763,101763,5171,7.733656,0.0,0.0,569.78,27.573007,27.573007,23.36,22.856630,5.224255e+02,4.859672,57.406009,15.56,23.36,34.34
0,e,101763,101763,8729,7.763136,0.0,0.0,16846621.12,20853.589876,20853.589876,2256.23,190570.469075,3.631710e+10,47.675743,2886.887210,564.73,2256.23,10193.24
0,b,101763,101763,315,7.956723,0.0,0.0,26.95,0.179164,0.179164,0.08,0.421842,1.779509e-01,16.015863,533.025299,0.03,0.08,0.19
0,t,101763,101763,8608,7.764119,0.0,0.0,935923.39,1141.357982,1141.357982,125.40,9862.747012,9.727378e+07,46.362719,2779.880331,31.38,125.40,565.92
0,lOCode,101763,101763,298,7.682557,0.0,0.0,2824.00,22.802453,22.802453,14.00,38.540820,1.485395e+03,15.961339,633.747325,7.00,14.00,26.00
0,lOComment,101763,101763,91,71.588888,0.0,0.0,344.00,1.773945,1.773945,0.00,5.902383,3.483812e+01,12.086676,353.045497,0.00,0.00,1.00
0,lOBlank,101763,101763,94,18.989220,0.0,0.0,219.00,3.979865,3.979865,2.00,6.382327,4.073410e+01,8.717249,166.015497,1.00,2.00,5.00
0,locCodeAndComment,101763,101763,29,91.929287,0.0,0.0,43.00,0.196604,0.196604,0.00,0.998901,9.978042e-01,11.108416,220.276481,0.00,0.00,0.00
0,uniq_Op,101763,101763,70,7.659955,0.0,0.0,410.00,11.896131,11.896131,11.00,6.749516,4.555597e+01,5.638606,274.147426,8.00,11.00,16.00
0,uniq_Opnd,101763,101763,176,7.729725,0.0,0.0,1026.00,15.596671,15.596671,12.00,18.064172,3.263143e+02,13.504800,502.394609,7.00,12.00,20.00
0,total_Op,101763,101763,623,7.698279,0.0,0.0,5420.00,57.628116,57.628116,30.00,104.537147,1.092802e+04,11.149832,264.091587,15.00,30.00,66.00
0,total_Opnd,101763,101763,485,7.762153,0.0,0.0,3021.00,39.249698,39.249698,20.00,71.691957,5.139737e+03,10.495967,225.713155,10.00,20.00,45.00
0,branchCount,101763,101763,144,0.000000,0.0,1.0,503.00,9.839549,9.839549,5.00,14.412698,2.077259e+02,8.568401,179.044387,3.00,5.00,11.00
0,index,101763,101763,101763,0.000983,0.0,0.0,101762.00,50881.000000,50881.000000,50881.00,29376.447720,8.629757e+08,0.000000,-1.200000,25440.50,50881.00,76321.50

In [75]:
outdf_numeric = outdf_numeric[
    (outdf_numeric['%Zero'] > 70.0) | (outdf_numeric['%Missing'] > 50.0)
]

In [76]:
outdf_numeric

,ColumnName,AllCounts,NotNullCounts,UniqueCounts,%Zero,%Missing,Min,Max,Mean,Average,Median,StddDev,Var,Skewness,Kurtosis,25Percentile,50Percentile,75Percentile
0,lOComment,101763,101763,91,71.588888,0.0,0.0,344.0,1.773945,1.773945,0.0,5.902383,34.838122,12.086676,353.045497,0.0,0.0,1.0
0,locCodeAndComment,101763,101763,29,91.929287,0.0,0.0,43.0,0.196604,0.196604,0.0,0.998901,0.997804,11.108416,220.276481,0.0,0.0,0.0

In [80]:
list(outdf_numeric['ColumnName'])

['lOComment', 'locCodeAndComment']

In [64]:
outdf_numeric

Empty DataFrame
Columns: [ColumnName, AllCounts, NotNullCounts, UniqueCounts, %Zero, %Missing, Min, Max, Mean, Average, Median, StddDev, Var, Skewness, Kurtosis, 25Percentile, 50Percentile, 75Percentile]
Index: []